name: CGL
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  cgl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2, composer-unused
          coverage: none

      # Validation
      - name: Validate composer.json
        run: composer validate

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - name: Lint composer.json
        run: composer lint:composer -- --dry-run

      - name: Lint Editorconfig
        run: composer lint:editorconfig

      - name: Lint PHP
        run: composer lint:php -- --dry-run --format=checkstyle

      - name: Lint Twig templates
        run: composer lint:twig

      - name: SCA PHP
        run: composer sca:php -- --error-format github

      - name: Rector migration
        run: composer migration:rector -- --dry-run

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
